CREATE DATABASE atv_lab02

USE atv_lab02

CREATE TABLE TB_FUNCIONARIO(
	MATRICULA			INT				NOT NULL,
	NM_FUNCIONARIO		VARCHAR(50)		NOT NULL,
	CPF					VARCHAR(20)		NOT NULL,
	DT_ADMISSAO			DATETIME		NOT NULL,
	PRIMARY KEY(MATRICULA)
)

--------------------------------------------------------

CREATE TABLE TB_PRODUTO(
	CD_PRODUTO			INT				NOT NULL,
	DS_PRODUTO			VARCHAR(50)		NOT NULL,
	CATEGORIA			VARCHAR(20)		NOT NULL,
	VALOR_ATUAL			FLOAT			NOT NULL,
	PRIMARY KEY(CD_PRODUTO)
)

--------------------------------------------------------

CREATE TABLE TB_VENDAS(
	CD_VENDA			INT				NOT NULL,
	MATRICULA			INT				NOT NULL		REFERENCES TB_FUNCIONARIO(MATRICULA),
	CD_PRODUTO			INT				NOT NULL		REFERENCES TB_PRODUTO(CD_PRODUTO),
	QUANTIDADE			INT				NOT NULL,
	VALOR_UNITARIO		FLOAT			NOT NULL,
	DT_VENDA			DATETIME		NOT NULL,
	PRIMARY KEY(CD_VENDA, MATRICULA, CD_PRODUTO)
)

--------------------------------------------------------

INSERT INTO TB_FUNCIONARIO
VALUES(1, 'JOSÉ', '011.222.333-44', '20230323'),
      (2, 'CAIO', '022.333.444-55', '20230324'),
	  (3, 'BRAD', '033.444.555-66', '20230325')

SELECT * FROM TB_FUNCIONARIO

--------------------------------------------------------

INSERT