CREATE DATABASE atv_lab01

USE atv_lab01

CREATE TABLE TB_DEPARTAMENTO(
	CD_DEPARTAMENTO		INT				NOT NULL		PRIMARY KEY,
	NM_DEPARTAMENTO		VARCHAR(20)		NOT NULL,
)

CREATE TABLE TB_FUNCIONARIO(
	CD_FUNCIONARIO		INT				NOT NULL			PRIMARY KEY,
	NM_FUNCIONARIO		VARCHAR(50)		NOT NULL,
	CPF					VARCHAR(20)		NOT NULL,
	CD_DEPARTAMENTO		INT				NOT NULL			REFERENCES TB_DEPARTAMENTO
)

CREATE TABLE TB_TELEFONE(
	CD_FUNCIONARIO		INT				NOT NULL			REFERENCES TB_FUNCIONARIO,
	NUMERO				VARCHAR(20)		NOT NULL,
	PRIMARY KEY(CD_FUNCIONARIO, NUMERO)
)

CREATE TABLE TB_CATEGORIA(
	CD_CATEGORIA		INT				NOT NULL			PRIMARY KEY,
	DESCRICAO			VARCHAR(60)		NOT NULL,
)

CREATE TABLE TB_TERCEIRIZADO(
	CD_TERCEIRIZADO		INT				NOT NULL			PRIMARY KEY,
	NM_TERCEIRIZADO		VARCHAR(50)		NOT NULL,
)

CREATE TABLE TB_ATENDE(
	CD_CATEGORIA		INT				NOT NULL			REFERENCES TB_CATEGORIA,
	CD_TERCEIRIZADO		INT				NOT NULL			REFERENCES TB_TERCEIRIZADO,
	PRIMARY KEY(CD_CATEGORIA, CD_TERCEIRIZADO)
)

CREATE TABLE TB_SOLICITACAO(
	CD_FUNCIONARIO		INT				NOT NULL			REFERENCES TB_FUNCIONARIO,
	CD_CATEGORIA		INT				NOT NULL			REFERENCES TB_CATEGORIA,
	DT_ABERTURA			DATETIME		NOT NULL,
	DT_FECHAMENTO		DATETIME		NULL,
	DS_PROBLEMA			VARCHAR(60)		NULL,
	STATUS				VARCHAR(50)		NOT NULL			DEFAULT('Em Aberto'),
	PRIMARY KEY(CD_FUNCIONARIO, CD_CATEGORIA, DT_ABERTURA)
)

ALTER TABLE TB_SOLICITACAO
ADD CONSTRAINT CK_STATUS CHECK (STATUS IN('Em Aberto', 'Fechado', 'Cancelado'))

ALTER TABLE TB_SOLICITACAO
ADD CONSTRAINT CK_STATUS_DATA
CHECK((STATUS = 'Em Aberto' AND DT_FECHAMENTO IS NULL) OR (STATUS IN ('Fechado', 'Cancelado') AND DT_FECHAMENTO IS NOT NULL))